### ISSUE TITLE
Custom validation does not behave as expected

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [formio/ngFormio#247]
Plunker for reference: https://plnkr.co/edit/Yd8VSRbSRLojY09MrJhY

I noticed when using the date-time control that the custom validation field errors when using String.replace to evaluate form values. While this does work for a good majority of values in other controls, String.replace will take the Date object and slip it into the custom validation code as-is, unquoted and all. This causes a syntax error when evaluated.

Another issue I noticed, when using scope.data in the custom code instead of the bracket notation, and I will make another issue if it helps with tracking, is that the scope values lag behind what has actually been chosen in the date-time picker. Say that when I load the form and select a date (say 11/18/2016), the custom validation code runs but prints 'undefined'. When I select another date (say 11/19/2016), then 11/18/2016 prints in the console.

**Comment by travist** [comment]
I just released a new version of the renderer @ v2.4.0-beta.1 which includes a complete revamp of how conditionals

**Comment by travist** [comment]
Thanks @blackbaud-jeremymorgan for reporting.  We will take a look.

**Comment by blackbaud-jeremymorgan** [comment]
Hey! Just wondering if there's been any movement on this issue. Its been a little quiet :)

**Comment by travist** [comment]
Hey @blackbaud-jeremymorgan sorry about that. I will have our PM add the investigation of this issue to the development backlog. Sorry for the delayed investigation.

**Comment by zackurben** [comment]
@blackbaud-jeremymorgan For this issue, `Another issue I noticed, when using scope.data in the custom code instead of the bracket notation, and I will make another issue if it helps with tracking, is that the scope values lag behind what has actually been chosen in the date-time picker. Say that when I load the form and select a date (say 11/18/2016), the custom validation code runs but prints 'undefined'. When I select another date (say 11/19/2016), then 11/18/2016 prints in the console.`

Use the `input` variable, for example, when checking the current field against a value:

`valid = input === 3`

As for the other issues, I'm in the process of fixing them now!
