### ISSUE TITLE
Checkbox checked by default?

### ISSUE THREAD

**Issue by heathdutton** [formio/ngFormio#301]
How does one make a checkbox checked by default? I've tried setting defaultValue to true, and it doesn't seem to do the trick?

http://codepen.io/heathdutton/pen/YNBKQN?editors=0010

**Comment by zackurben** [comment]
@heathdutton The defaultValue is working as expected, but the editor component does not fully represent the final state of the component, for performance purposes.

I've had to edit the codepen because there was a rogue `]` character in the json, but this works as intended: http://codepen.io/anon/pen/GrzRqX?editors=0010

Here is where the updates are live;
https://monosnap.com/file/QqgzpDsN4Cga9s3amJIkx5ZJeZGoc4
https://monosnap.com/file/eNxQD0PEprGXVtAP9w3X012XgmkiqA

And the component editor view: 
https://monosnap.com/file/KHBEvj26zO16QyUxhY2iTUbwjAy4LC

Best regards,
Zack Urben.
