### ISSUE TITLE
Translation issue with v3.10.3

### ISSUE THREAD

**Issue by nfernand** [formio/ngFormio#636]
OS : Windows
Browser : Chrome 71.0.3578.98
ngFormio version : v3.10.3
angularjs version : 1.7.5

**Issue**
We previously implemented form translation support as described here : https://github.com/formio/ngFormio/wiki/Translating-a-form
The form was being properly translated when using ngFormio v2.36.3.

However, when upgrading ngFormio to v3.10.3, the form stopped being translated.
On runtime inspection, we do step through $translate.use() and the custom loader properly pulls localisation data but the form stays in english.

**Comment by randallknutson** [comment]
ngFormio 2.x is a renderer designed in angular1. ngFormio 3.x is a wrapper around our javascript only form renderer. This allows all forms to work the same regardless of the framework you are using. However, because of this the way translations work has changed from 2.x to 3.x. 

You can see the new way that translations are done here: http://formio.github.io/formio.js/app/examples/language.html
