### ISSUE TITLE
Advanced Condition Does not work inside table.

### ISSUE THREAD

**Issue by Morshed0308** [formio/ngFormio#664]
I have made a form where I used a **Table** inside of a **Datagrid**. I have added a html component under a  select component and added advanced logic that it will show upon a special value selected in a select component. But it is not working . How can I do this inside a table . @travist @randallknutson

**Comment by jhen1422** [comment]
@Morshed0308 When triggering logic inside a data grid or edit grid, you need to use the 'row' variable instead of 'data'.

Here's example javascript code to display html component based on the value of a select component inside a datagrid.

show = row.select === 'test';

('select' being the API key of the Select component and 'test' being the value from the select that will trigger the logic)

**Comment by Morshed0308** [comment]
Thanks @jhen1422
